name: 'transformer'
version: '1.0.0'
profile: 'transformer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  transformer:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    reports:
      +materialized: table
      +schema: reports

vars:
  session_default_duration_minutes: 30
  orphan_booking_threshold_pct: 5.0
